TESTDIR = .

all: tests

tests:
	$(TESTDIR)/intervalBed_test.sh
	$(TESTDIR)/mergePileupColumns_test.sh
	$(TESTDIR)/pileup2pro_test.sh
	$(TESTDIR)/windowWig_test.sh
	$(TESTDIR)/fai2Bed_test.sh

.PHONY: tests

